# First stage: builder
FROM python:3.11-slim AS builder

WORKDIR /code

COPY requirements.txt .

# Install Python packages
RUN pip3 install --no-cache-dir -r requirements.txt

# Second stage: final image
FROM ubuntu:22.04 AS final

# Set the working directory
WORKDIR /code

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3.11 python3.11-dev python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Copy the installed packages from the builder stage
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/dist-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy the application code
COPY . .

EXPOSE 8501
# Set the entry point to Bash
CMD ["python", "-m", "streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]

